version: 2.1
jobs:
  build:
    #working_directory: ~/angular-baseball
    docker:
        - image: 'circleci/node:latest'
    environment:
        CHROME_BIN: '/usr/bin/google-chrome karma start --single-run'
    steps:
        - checkout
        - run:
            name: 'List'
            command: |
                ls -al
                cd angular-baseball
                ls -al
        - run:
            name: 'Install'
            command: |
                cd angular-baseball
                npm install
                ls -al
        - run:
            name: 'Tests'
            command: |
                cd angular-baseball
                npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
                ls -al
                npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
                ls -al
