version: 2.1
jobs:
  build:
    #working_directory: ~/angular-baseball
    docker:
        - image: 'circleci/node:latest'
    steps:
        - checkout
        - run:
            name: 'List'
            command: |
                ls -al
                cd angular-baseball
                ls -al
        - run:
            name: 'Install'
            command: |
                cd angular-baseball
                npm install
                ls -al
